"""initial schema

Revision ID: 85b9969d21f9
Revises: 
Create Date: 2026-07-03 10:53:02.325871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b9969d21f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('niveau', sa.String(length=16), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sexe', sa.String(length=1), nullable=False),
    sa.Column('poids_kg', sa.Float(), nullable=False),
    sa.Column('taille_cm', sa.Float(), nullable=False),
    sa.Column('diagnostic', sa.Text(), nullable=False),
    sa.Column('chirurgien', sa.String(length=128), nullable=False),
    sa.Column('specialty', sa.String(length=32), nullable=False),
    sa.Column('urgence', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('rpps', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_pending_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_recovery_codes', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dicom_series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('study_uid', sa.String(length=256), nullable=False),
    sa.Column('series_uid', sa.String(length=256), nullable=False),
    sa.Column('modality', sa.String(length=8), nullable=False),
    sa.Column('slice_thickness_mm', sa.Float(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('cols', sa.Integer(), nullable=True),
    sa.Column('num_slices', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=16), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_uid')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('mesh_ref', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volumetrie_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('organ_volume_ml', sa.Float(), nullable=False),
    sa.Column('lesion_volume_ml', sa.Float(), nullable=False),
    sa.Column('ratio_lesion_organe_pct', sa.Float(), nullable=True),
    sa.Column('volume_resection_ml', sa.Float(), nullable=True),
    sa.Column('remnant_pct', sa.Float(), nullable=False),
    sa.Column('flr_threshold_pct', sa.Float(), nullable=True),
    sa.Column('flr_safe', sa.Boolean(), nullable=True),
    sa.Column('flr_bw_pct', sa.Float(), nullable=True),
    sa.Column('bsa_m2', sa.Float(), nullable=True),
    sa.Column('margin_cm', sa.Float(), nullable=True),
    sa.Column('is_cirrhotic', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volumetrie_results')
    op.drop_table('segments')
    op.drop_table('dicom_series')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
